variable "env" {}
variable "docdb" {}
variable "rds" {}
variable "elasticcache" {}
variable "rabbitmq" {}
variable "alb" {}
variable "app" {}
variable "bastion" {}
variable "vpc" {}
variable "tags" {}